"""add task.stage

Revision ID: 6466311725e3
Revises: 5250bcdd9fc7
Create Date: 2023-06-26 16:47:21.460746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6466311725e3'
down_revision = '5250bcdd9fc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('board', sa.Enum('Plans', 'Actual', 'Complete', name='board'), nullable=True))
    op.add_column('tasks', sa.Column('stage', sa.Enum('Dev', 'Qa', 'Review', 'Release', 'Done', 'Not_started', name='stage'), server_default='Not_started', nullable=True))
    op.alter_column('tasks', 'board',
               existing_type=postgresql.ENUM('Actual', 'Complete', 'Plans', 'Release', name='board'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'board',
               existing_type=postgresql.ENUM('Actual', 'Complete', 'Plans', 'Release', name='board'),
               nullable=True)
    op.drop_column('tasks', 'stage')
    op.drop_column('history', 'board')
    # ### end Alembic commands ###
