"""edit task.stage

Revision ID: 6ffe3d28608d
Revises: 48d00da5c1b2
Create Date: 2023-05-05 15:20:16.279273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ffe3d28608d'
down_revision = '48d00da5c1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('stage', postgresql.ENUM('Dev', 'Qa', 'Review', 'Release', 'Done', 'Not_started', name='stage'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
