"""ДОбавил добавление подзадач

Revision ID: 880c2a4278bb
Revises: e91d77783441
Create Date: 2023-04-11 13:04:38.144215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '880c2a4278bb'
down_revision = 'e91d77783441'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###
