"""edit task.stage_2

Revision ID: 42602044fd79
Revises: 6ffe3d28608d
Create Date: 2023-05-05 15:21:09.168851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42602044fd79'
down_revision = '6ffe3d28608d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('stage', sa.Enum('Dev', 'Qa', 'Review', 'Release', 'Done', 'Not_started', name='stage'), server_default='Not_started', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'stage')
    # ### end Alembic commands ###
