"""add field task.importance

Revision ID: f09c0e9c86f9
Revises: e6d7194f5325
Create Date: 2023-04-29 12:51:12.968932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09c0e9c86f9'
down_revision = 'e6d7194f5325'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('importance', sa.Enum('high', 'medium', 'normal', 'low', name='importance'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'importance')
    # ### end Alembic commands ###
