"""Change model Users

Revision ID: b2f4d4b1c9df
Revises: 42602044fd79
Create Date: 2023-05-09 15:53:24.356134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f4d4b1c9df'
down_revision = '42602044fd79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('banned', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('users', sa.Column('deleted', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'deleted')
    op.drop_column('users', 'banned')
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'city')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
