"""hisory

Revision ID: 049c1981c570
Revises: ca62e12f1c30
Create Date: 2023-06-01 17:19:29.817933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049c1981c570'
down_revision = 'ca62e12f1c30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_task_id_fkey', 'history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('history_task_id_fkey', 'history', 'tasks', ['task_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
