"""update task.STAGE

Revision ID: 4b1ef3ff19cd
Revises: ab8786624835
Create Date: 2023-04-18 10:46:35.464546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b1ef3ff19cd'
down_revision = 'ab8786624835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE IF EXISTS stage')
    op.execute("""
    create type stage as ENUM ('Dev', 'Qa', 'Review', 'Release', 'Done')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE stage')
    # ### end Alembic commands ###
