"""task.stage

Revision ID: a65162fe063c
Revises: 4b1ef3ff19cd
Create Date: 2023-04-18 11:10:11.214390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a65162fe063c'
down_revision = '4b1ef3ff19cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
