"""add foto from user

Revision ID: 3cd75dcaa1a4
Revises: 6466311725e3
Create Date: 2023-07-03 14:43:10.592674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cd75dcaa1a4'
down_revision = '6466311725e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_assets')
    # ### end Alembic commands ###
