"""remove table card

Revision ID: 8edd970f8753
Revises: a3fa804ac378
Create Date: 2023-07-13 18:42:06.727905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8edd970f8753'
down_revision = 'a3fa804ac378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
