"""add task.status - delete

Revision ID: 2e4dfd40bde8
Revises: 84489f117599
Create Date: 2023-05-05 11:18:10.910335

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2e4dfd40bde8'
down_revision = '84489f117599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### 'Created', 'Deleted'
    op.execute("ALTER TYPE task_status ADD VALUE 'Created'")
    op.execute("ALTER TYPE task_status ADD VALUE 'Deleted'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
