"""del column history.board stage task_status

Revision ID: 3f54462410ce
Revises: ca556e4f061f
Create Date: 2023-05-03 12:34:52.702806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f54462410ce'
down_revision = 'ca556e4f061f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'board')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('board', postgresql.ENUM('Actual', 'Complete', 'Plans', 'Release', name='board'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
