"""add column project.title_en и role.membership_proj

Revision ID: a3fa804ac378
Revises: 5d0516c00930
Create Date: 2023-07-13 16:08:38.248661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3fa804ac378'
down_revision = '5d0516c00930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('project_membership', postgresql.ARRAY(sa.String(length=32), zero_indexes=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'project_membership')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'title_en')
    # ### end Alembic commands ###
