"""add field task.importance

Revision ID: e6d7194f5325
Revises: a65162fe063c
Create Date: 2023-04-29 12:31:08.789227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d7194f5325'
down_revision = 'a65162fe063c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('DROP TYPE IF EXISTS importance')
    op.execute("""
        create type importance as ENUM ('high', 'medium', 'normal', 'low')
        """)
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('drop type importance;')
    # ### end Alembic commands ###
