"""add task.project

Revision ID: 5d0516c00930
Revises: 557c52416250
Create Date: 2023-07-11 21:28:30.091505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0516c00930'
down_revision = '557c52416250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('tasks_project_id', 'tasks', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_project_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###
