"""Add column CommentsTask.created

Revision ID: ab8786624835
Revises: 1d6723aeef97
Create Date: 2023-04-15 19:19:59.728054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab8786624835'
down_revision = '1d6723aeef97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_comments', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_comments', 'created')
    # ### end Alembic commands ###
