"""add column history.board stage task_status

Revision ID: 52c107105452
Revises: 3f54462410ce
Create Date: 2023-05-03 12:35:20.043563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c107105452'
down_revision = '3f54462410ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('stage', sa.Enum('Dev', 'Qa', 'Review', 'Release', 'Done', name='stage'), nullable=True))
    op.add_column('history', sa.Column('task_status', sa.Enum('Job', 'Pause', 'Complete', 'Project', name='task_status'), nullable=True))
    op.add_column('history', sa.Column('board', sa.Enum('Plans', 'Actual', 'Pause', 'Complete', name='board'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'board')
    op.drop_column('history', 'task_status')
    op.drop_column('history', 'stage')
    # ### end Alembic commands ###
