"""modify CARD

Revision ID: e91309a56154
Revises: 1fafe213696d
Create Date: 2023-06-09 10:58:48.413439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91309a56154'
down_revision = '1fafe213696d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'subcategory')
    # ### end Alembic commands ###
