"""add model User Task History

Revision ID: 4563f7ce6458
Revises: 
Create Date: 2023-04-05 16:11:28.115699

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4563f7ce6458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('board', sa.Enum('Actual', 'Complete', 'Plans', 'Release', name='board'), nullable=True),
                    sa.Column('task_status', sa.Enum('Job', 'Pause', 'Complete', 'Project', name='task_status'),
                              nullable=True),
                    sa.Column('stage', sa.Enum('Dev', 'Qa', 'Review', 'Release', 'Done', 'Not_started', name='stage'), nullable=True),
                    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=True),
                    sa.Column('task_status', sa.Enum(name='task_status'), nullable=True),
                    sa.Column('board', sa.Enum(name='board'), nullable=True),
                    sa.Column('stage', sa.Enum(name='stage'), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], onupdate='CASCADE', ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('tasks')
    op.drop_table('users')
    op.execute('drop type stage;')
    op.execute('drop type board;')
    op.execute('drop type task_status;')
    # ### end Alembic commands ###
