"""add add column task.seadline task.estimate task.tags 

Revision ID: 51a4b3ee29ae
Revises: 97d4b2daab16
Create Date: 2023-04-10 21:16:29.158424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51a4b3ee29ae'
down_revision = '97d4b2daab16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('estimate', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'estimate')
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
