"""ДОбавил task. tags

Revision ID: e91d77783441
Revises: 901783b6d190
Create Date: 2023-04-11 12:53:06.219085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e91d77783441'
down_revision = '901783b6d190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tags')
    # ### end Alembic commands ###
